os:
- osx
language: generic
env:
  - PYTHON=3.6.4 NODE=9

before_install:
  - brew update
  - brew install openssl readline
  - brew upgrade pyenv nvm
  - pyenv install $PYTHON
  - export PYENV_VERSION=$PYTHON
  - export PATH="/Users/travis/.pyenv/shims:${PATH}"
  - python -m venv venv
  - source venv/bin/activate
  - python --version
  - nvm install %NODE
  - nvm use %NODE
install:
  - python -m pip install -U pip
  - pip install -r requirements-dev.txt
  - npm install -g yarn
  - cd client && yarn && cd ..
script:
  - cd client && yarn build && cd ..
  - python setup.py bdist_mac
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: XpQRepHdIvSIFfaS1UGKcDnV5wKdduWJilnRCK530igDJT9Abzr2AHIN501nBaTFHT6Si/vO/ArUaziq9vyBo07JlNFu5s9lLyt0f5WRBkRHYcCdu3AKJGYE0iYN7VYeOUXq+aCdtC1gaLxf8dcj0wjB4cvGJw7f5jT85WwbAktt2212TDh+aaLTuVlRTVeHROkleDAJR1FoV+7nvpgPKid5C9cHthaULdn0XelYjmQcHuxkKXlpp5VfUVvLc2PT2GM/RqWwoMztVs9U3DrxoJTl0BBohvCWta9b/JOqpStHvPjGvp6WTucTLS1pcsRWmjIsLJFhaAvc3d1BcT0fRaswkwpntKHWXOBqCeq1pVgmWbuiS/znIXapoUslzO3fX3klUwH4GsylgNFOxmNOhAneaIo/D1KESAlxx/2MFioQ1DXJ8OWx9O80YjlTHiM+GZo06VCn5fQW6UdFp1InL9ocC+DHAZrhdzGfdNo8sFLtALk80PSANYXpbX+OG3Mu0ezzAmryIaLB3ae1VOoRopMt+pCyCQ6fnKJ18vyukQ+hIy7+FTQ8rXofV5eC161Bymbsz/iTkR1CxNecvnbF3aJHCrnraaAWfidML3xuOf8OpiZxlzNQkOnl7RoueOHFOLBZ3pRw9rtFAAg/C28/4iTmq7KH/hyzul0LrPZjwMo=
